### ISSUE TITLE
travis failing

### ISSUE THREAD

**Issue by amoffat** [amoffat/snake#2]
https://travis-ci.org/amoffat/snake/builds/62934759

Can't reproduce this failure locally using same version of Vim and Python.  Any help would definitely be appreciated

```
11.22s$ python tests.py
...........F.........FE......
======================================================================
ERROR: test_let (__main__.VariableTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 398, in test_let
    self.assertEqual(output["original"], None)
TypeError: 'NoneType' object has no attribute '__getitem__'
======================================================================
FAIL: test_abbrev_fn (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 173, in test_abbrev_fn
    self.assertEqual(changed, "1 2\n")
AssertionError: u'\n' != '1 2\n'
======================================================================
FAIL: test_set_buffer_contents (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 150, in test_set_buffer_contents
    self.assertEqual(changed, "new stuff")
AssertionError: u'The quick brown fox jumps over the lazy dog' != 'new stuff'
----------------------------------------------------------------------
Ran 29 tests in 11.116s
FAILED (failures=2, errors=1)
```

**Comment by hoelzro** [comment]
@amoffat are you using the exact same version of vim and python locally?

**Comment by amoffat** [comment]
It does look like Travis is using Vim 7.3, and I'm on 7.4.  Time to install 7.3...

**Comment by hoelzro** [comment]
@amoffat make sure you have the patch level right, too; a lot of distributions use a patch level above just Vim X.Y

**Comment by amoffat** [comment]
upgraded vim on the travis vms to 7.4.  7.3 be damned, for now

**Comment by hoelzro** [comment]
@amoffat You might want to check `v:version` to make sure people don't try snake with earlier versions
