### ISSUE TITLE
U flag to open causing a python-3.11 failure, aka are you continuing snake?

### ISSUE THREAD

**Issue by abadger** [amoffat/snake#33]
Hey, I'm wondering if you are going to continue working on  snake.  I just upgraded to 3.11 and noticed that changes to open() (the "U" flag has gone away) is causing a failure:

```
Error invoking 'python_execute_file' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "/home/badger/.vim/pack/badger/start/snake/plugin/bootstrap.py", line 11, in <module>
    import snake
  File "/home/badger/.vim/pack/badger/start/snake/plugin/snake/__init__.py", line 737, in <module>
    from . import plugin_loader
  File "/home/badger/.vim/pack/badger/start/snake/plugin/snake/plugin_loader.py", line 215, in <module>

    import_source("vimrc", vimrc_path)
  File "/home/badger/.vim/pack/badger/start/snake/plugin/snake/plugin_loader.py", line 206, in import_s
ource
    h = open(path, desc[1])
        ^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'U'
```

If you're going to continue work on snake, I can look at opening a PR to omit the flag when we are using later python versions.  There are other deprecations in the works, though (for instance, imp is deprecated) so I'll probably try porting my configs to lua if you don't have time to keep snake updated anymore.

**Comment by amoffat** [comment]
Hi @abadger, no I am not working on snake anymore. I should probably archive it, unless you would be interested in maintaining it?

**Comment by abadger** [comment]
Unfortunately no. Not enough time right now
