### ISSUE TITLE
Expression invalide : mapleader

### ISSUE THREAD

**Issue by boussouira** [amoffat/snake#8]
After install i tryed the &lt;leader&gt;r code from the readme file, when i type \r i get this error:
```
Erreur détectée en traitant  :                                                                                                                        
E121: Variable non définie : mapleader
E15: Expression invalide : mapleader
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.vim/bundle/snake/plugin/snake/__init__.py", line 54, in dispatch_mapped_function
    return fn()
  File "/home/user/.vimrc.py", line 5, in reverse
    replace_word(get_word()[::-1])
  File "/home/user/.vim/bundle/snake/plugin/snake/__init__.py", line 211, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/.vim/bundle/snake/plugin/snake/__init__.py", line 334, in get_word
    keys("yiw")
  File "/home/user/.vim/bundle/snake/plugin/snake/__init__.py", line 313, in keys
    k = _LEADER_REGEX.sub(get_leader(), k)
  File "/home/user/.vim/bundle/snake/plugin/snake/__init__.py", line 304, in get_leader
    return vim.eval("mapleader")
vim.error: expression invalide
```

**Comment by amoffat** [comment]
Hey @boussouira, could you dump `vim --version` here?

**Comment by boussouira** [comment]
Sure, I'm using Kubnutu 14.04
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:40:04)
Rustines incluses : 1-52
Modifié par pkg-vim-maintainers@lists.alioth.debian.org
Compilé par buildd@
Énorme version sans interface graphique.
  Fonctionnalités incluses (+) ou non (-) :
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
         fichier vimrc système : "$VIM/vimrc"
     fichier vimrc utilisateur : "$HOME/.vimrc"
 2me fichier vimrc utilisateur : "~/.vim/vimrc"
      fichier exrc utilisateur : "$HOME/.exrc"
               $VIM par défaut : "/usr/share/vim"
Compilation : gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Édition de liens : gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-i386-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions      
```

**Comment by amoffat** [comment]
@boussouira give it a try now

**Comment by boussouira** [comment]
Fixed.
Thank you for your fast response and this great project.

**Comment by amoffat** [comment]
you got it :+1:
